### ISSUE TITLE
Apple TV+ DRM

### ISSUE THREAD

**Issue by emmetgrand** [yusifsalam/t490-macos#25]
How to make Apple TV+ work? I have the latest versions of Lilu and WhateverGreen.kext - not working.

**Comment by yusifsalam** [comment]
Need a bit more info: your hardware (gpu, cpu), what have you tried, what exactly is the error you're getting. 

Otherwise, refer to this https://dortania.github.io/OpenCore-Post-Install/universal/drm.html. I personally don't have AppleTV+ so can't test myself but at least one other person got AppleTV+ working with this EFI.

**Comment by emmetgrand** [comment]
![Screenshot 2020-11-11 at 22 19 51](https://user-images.githubusercontent.com/69478828/98854924-46edf580-246c-11eb-97a4-5efeddd5a4aa.png)

I just thought based on the description that this function works for you)

**Comment by yusifsalam** [comment]
We'd need your actual hardware info, the screenshot is only showing what we defined in config.plist (and you probably don't want to show your serial number). Also, can you describe in detail what's actually not working? Does it start playback then stop, does it never start playback or something else?

I personally only tested Netflix and it uses the same DRM as ATV+ if I'm not mistaken, so in theory it should work too.

**Comment by yusifsalam** [comment]
Closing, since no response in 7 days.
