### ISSUE TITLE
Thunderbolt not working

### ISSUE THREAD

**Issue by tungmeister** [yusifsalam/t490-macos#32]
Hi, Thanks for all the hard work - I've setup using the github config and everything appears to be working pretty much perfectly other than thunderbolt - under hardware thunderbolt is showing no drivers loaded and I'm only getting display output via the lenovo dock. Could you assist?
EDIT: The dock works via the USB C port but not the integrated thunderbolt in the power connector

**Comment by yusifsalam** [comment]
Sorry I can't really help with Thunderbolt, since I don't use it/don't have the hardware to test. 

Have you made your own USB map? Does the top port work for data transfer? 

For further research, I can point you to this repo https://github.com/tylernguyen/x1c6-hackintosh. Hardware is very similar and they seem to have fully functional TB.

**Comment by yusifsalam** [comment]
Closing since no response from author.
