### ISSUE TITLE
Battery indicator and touchpad not working properly

### ISSUE THREAD

**Issue by Jpeace7** [yusifsalam/t490-macos#6]
Salam 

Really nice work , everything worked but the battery indicator ( it continuously unchecks itself ) and the touchpad it works like a mouse only . Is there a way to enable the Tap instead of using buttons . Any info would be greatly appreciated

**Comment by yusifsalam** [comment]
Hi and thanks!

What do you mean by battery unchecking itself, can you provide screenshots or video?
For the touchpad, open system preferences - trackpad - and enable tap to click. You can find more info [here](https://osxdaily.com/2014/01/28/enable-tap-to-click-mac-trackpad/). Does that help?

**Comment by Jpeace7** [comment]
The issue I’m Getting with trackpad is not found , under mouse I can change settings but no tap  is available . And for the battery ounce I get home I’ll take a video , thanks again sorry for the late reply

**Comment by Jpeace7** [comment]
![1903805F-6134-4CDA-BC9E-93E14AE5F1A8](https://user-images.githubusercontent.com/67621911/89255146-d5cdb500-d5d5-11ea-955f-d5c66bf3462c.jpeg)

**Comment by Jpeace7** [comment]
I can’t post a video , basically I can’t check show battery status in menu bar  and the battery setting are always like that I can’t change it . 
![image](https://user-images.githubusercontent.com/67621911/89256345-c00dbf00-d5d8-11ea-9312-ba20072399bd.jpg)

![image](https://user-images.githubusercontent.com/67621911/89256247-889f1280-d5d8-11ea-98e3-e54b4b98d0c5.jpg)

**Comment by yusifsalam** [comment]
I see, it seems like you have a different battery from my T490. Is your laptop also a Thinkpad T490? Do you know the exact model number for the laptop and part number for the trackpad?

**Comment by Jpeace7** [comment]
Yea it is , it’s t490 20N3 -S5XF01 
Touchpad part number is 01YU054

**Comment by yusifsalam** [comment]
If you could also attach an IORegistry log, that would help a lot. 
For the battery I'm not really sure to be honest, it should work, because my laptop is also 20N3. What is your bios and EC version?
For the trackpad, can you run ```kextstat|grep -I voodoo``` and check that voodooinput is loaded. You could try to disable SSDT-Thinkpad_Trackpad.aml and see if that changes anything. If that still is of no help, you could also try VoodooRMI for the trackpad driver which is way smoother in my opinion but lacked the trackpad button support last I tried it so I decided to stick with the VoodooPS2 driver. I have a separate branch for the RMI driver to get you started on that, you should still update to the latest kext version if you decide to give it a go.

**Comment by Jpeace7** [comment]
voodooinput doesn't load , also voodooPs2 supersedes everything if I try anything else the system doesn't boot and I have to boot recovery . as far as IOregistry what part do you need to look at , I can only take a screenshot . I think I need to flash the firmware and update the bios then give it another go , if only I can fix the battery ,touchpad and Bluetooth  dieing after it wakes from sleep . it would be solid

**Comment by yusifsalam** [comment]
I just updated the bluetooth and VoodooPS2 kexts to the latest versions in the master branch, which should fix at least some of the sleep issues with bluetooth. 
Can you verify that you have the VoodooPS2 kext configured like it is [here](https://github.com/yusifsalam/t490-macos/blob/d649eba855374f0459ea7f452f0c8d192be94cea/OC/config.plist#L872-L949), specifically the order is important - VoodooInput should come before everything else from VoodooPS2. Also make sure that VoodooPS2 actually has the required plugins inside it (which were removed in the VoodooRMI branch of my repo) - if you right click the kext and then click show contents, navigate to the plugins folder, it should have the VoodooInput, Mouse, Trackpad and Keyboard kexts there. If those are not present, you'll have to replace the VoodooPS2 kext file with the one from [here](https://github.com/acidanthera/VoodooPS2/releases/tag/2.1.6). 
As for the IORegistry, i wanted to check that the VoodooTrackpad device is attached but since VoodooInput isn't loading the kext on your machine, this isn't needed anymore until you can actually get VooodooInput to load correctly.

**Comment by Jpeace7** [comment]
I just don't have voodoo input , everything else is inorder. inside voodooPS2 Voodooinput is there .

**Comment by yusifsalam** [comment]
You don't need to have it separately, it's included in VoodooPS2.

**Comment by Jpeace7** [comment]
understood with the new voodooPS2 . voodoo input is loading . nothing changed though

**Comment by yusifsalam** [comment]
Can you check in IORegistryExplorer that the TouchPad device is attached?
![Näyttökuva 2020-8-4 kello 11 35 03](https://user-images.githubusercontent.com/42574232/89272328-a86d1f80-d646-11ea-9aa2-8b1e8ec1387a.png)

**Comment by Jpeace7** [comment]
![0F8EAB37-33AF-44D2-B14E-9DFE181682E6](https://user-images.githubusercontent.com/67621911/89273095-f147b880-d5f3-11ea-8933-ffccb1b4f5a9.jpeg)

**Comment by yusifsalam** [comment]
It looks good to me so I'm afraid I don't have any other ideas off the top of my head other than you update to the latest firmware and try again from scratch.

**Comment by Jpeace7** [comment]
ok ill try that , thank you very much for your help , you rock !

**Comment by yusifsalam** [comment]
Closing this for now due to inactivity and since I'm not able to replicate the issues.
